---
version: "3"
services:
  posterizarr:
    hostname: "posterizarr"
    container_name: "posterizarr"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: "unless-stopped"
    user: "1000:1000"
    ports:
      - "8000:8000"
    networks:
      - "proxy"
    volumes:
      - "/opt/appdata/posterizarr:/config:rw"
      - "/opt/appdata/kometa/assets:/assets:rw"
      - "/opt/appdata/posterizarr/assetsbackup:/assetsbackup:rw"
      - "/opt/appdata/posterizarr/manualassets:/manualassets:rw"
networks:
  proxy:
    driver: bridge
    external: true
