name: Build ImageMagick Base Image

on:
  workflow_dispatch:

jobs:
  build-base:
    name: Build and Push ImageMagick Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Get latest ImageMagick version
        id: imagemagick_version
        run: |
          # Fetch the raw version file and extract the version string using grep and sed
          version=$(curl -s https://raw.githubusercontent.com/SoftCreatR/imei/main/versions/imagemagick.version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+-[0-9]+')
          echo "IMAGEMAGICK_VERSION=$version" >> $GITHUB_ENV
          echo "Latest ImageMagick version: $version"

      - name: Build and Push Base Image
        uses: docker/build-push-action@v5
        with:
          context: ./imagemagick-base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/fscorrupt/posterizarr-base:${{ env.IMAGEMAGICK_VERSION }}
            ghcr.io/fscorrupt/posterizarr-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
